# Generated by Django 4.2.4 on 2023-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.AddField(
            model_name='genre',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='genres', to='bookshop.book'),
        ),
    ]
