# Generated by Django 4.2.4 on 2023-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_remove_publisher_books_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='bookshop.book'),
        ),
    ]
