# Generated by Django 4.2.4 on 2023-09-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_remove_author_books_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('building_number', models.PositiveSmallIntegerField(null=True)),
                ('apartment', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Canceled'), (1, 'Placed'), (2, 'In Delivery'), (3, 'Delivered'), (4, 'Delayed')])),
                ('books', models.ManyToManyField(related_name='orders', to='bookshop.book')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bookshop.address')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bookshop.shippingmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=128)),
                ('last_name', models.CharField(db_index=True, max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookshop.address')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookshop.order')),
            ],
        ),
    ]
