# Generated by Django 4.2.4 on 2023-09-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0011_remove_customer_address_customer_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addresses',
            new_name='address',
        ),
    ]
