# Generated by Django 4.2.4 on 2023-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0014_remove_customer_address_customer_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='orders', to='bookshop.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Canceled'), (1, 'Placed'), (2, 'In delivery'), (3, 'Delivered'), (4, 'Delayed')]),
        ),
    ]
