# Generated by Django 4.2.4 on 2023-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0018_remove_customer_orders_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='customer', to='bookshop.order'),
        ),
    ]
